### ISSUE TITLE
The following components and platforms could not be set up:

### ISSUE THREAD

**Issue by sblantipodi** [korylprince/hassio-apcupsd#14]
HA 0.98.3 on a Raspberry 64 bit hassio image running on a Pi4 4GB.
Using Cyberpower PR1500ELCD here that is pretty identical to APC SMT1500i

When I start HA I have this message:
The following components and platforms could not be set up:
apcupsd
apcupsd.binary_sensor
apcupsd.sensor
Please check your config.

this is my config in the config.yaml

```
apcupsd:
  host: a722577e-apcupsd
  
# Sensors
binary_sensor:
  - platform: apcupsd
  
sensor:
  - platform: apcupsd
    resources:
      - bcharge
      - version
      - upsmode
      - model
      - status
      - linev
      - loadpct
      - bcharge
      - timeleft
      - mbattchg
      - mintimel
      - maxtime
      - maxlinev
      - minlinev
      - outputv
```

System logs shows this error:
```
19-09-05 19:39:29 INFO (MainThread) [hassio.core] Hass.io is up and running
19-09-05 19:39:44 WARNING (MainThread) [hassio.api.addons] Protected flag changing for a722577e_apcupsd!
19-09-05 19:39:47 INFO (SyncWorker_16) [hassio.docker.interface] Clean addon_a722577e_apcupsd application
19-09-05 19:39:48 ERROR (SyncWorker_16) [hassio.docker] Can't start addon_a722577e_apcupsd: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/usb/": no such file or directory")
```

this commands shows the UPS:
```
core-ssh:~# cat /sys/bus/usb/devices/*/product
PR1500ELCD
USB2.0 Hub
xHCI Host Controller
xHCI Host Controller
DWC OTG Controller
```

```
core-ssh:/dev# ls /dev
fd       full     init     mqueue   null     ptmx     pts      random   shm      stderr   stdin    stdout   tty      ttyAMA0  urandom  zero
```

Addons does not even start and there is no log in the logs section of the addon
